routes/user.py
import json
from flask import (
    render_template,
    session,
    request,
    url_for,
    redirect,
    flash,
    abort,
    jsonify
)
from sqlalchemy.exc import IntegrityError
from flask import current_app
import datamodels
from datamodels.enums import PreferenceTags
from dataforms import (
    AddUserForm,
    EditUserForm,
    LoginForm,
    AjaxCSRFTokenForm,
    CustomSettingForm,
)

from utils.base import get_current_user
from .decorators import login_required
from .utils import get_session_data, set_session_data
from utils.images import generate_thumbnail
from .blueprint import SubdomainBlueprint
from six.moves.urllib.parse import urlencode

blueprint = SubdomainBlueprint("user", __name__, template_folder="templates")


def merge_anonymous_data(user_id, data):
    for seg_id in data:
        datamodels.SegmentUserProgress.save_user_progress(
            seg_id, user_id, int(data[seg_id])
        )


def merge_anonymous_surveys_data(user_id, data):
    for seg_id in data:
        response = datamodels.SegmentSurveyResponse()
        response.segment_id = seg_id
        response.user_id = user_id
        response.answers = json.dumps(data[seg_id])
        response.save()


@blueprint.subdomain_route("/user/<slug>", methods=["GET"])
def view(slug, institute=""):
    """ View a user's profile. """
    user_id = slug
    user = datamodels.get_user(user_id)
    data = {"user": user, "form": EditUserForm()}
    return render_template("user.html", **data)


@blueprint.subdomain_route("/edit", methods=["GET"])
@login_required
def retrieve(user, institute=""):
    """
    Get the current user data.
    """
    return render_template("user_edit.html", **{"form": EditUserForm()})


@blueprint.subdomain_route("/edit", methods=["POST"])
@login_required
def edit(user, institute=""):
    """
    Edit the current user.
    """

    data = {"errors": [], "message": "Error while saving data"}
    db = datamodels.get_session()

    if "profile_picture" in request.form:
        form = AjaxCSRFTokenForm(request.form)
        if form.validate():
            file = request.files["file"]

            try:
                filename = generate_thumbnail(file, "square_l")
            except ValueError as e:
                data["errors"].append(str(e))
                return jsonify(data), 400
            if not filename:
                data["errors"].append("Couldn't upload picture.")
            else:
                user.profile_picture = filename
                db.add(user)
                db.commit()
        else:
            data["errors"].append("Missing CSRF token")

        if data["errors"]:
            return jsonify(data), 400
        else:
            return jsonify({"message": "Changes saved", "errors": []})

    form = EditUserForm(request.form)
    if form.validate():
        try:
            user.email = form.email.data.lower()
            user.first_name = form.first_name.data
            user.last_name = form.last_name.data
            user.username = form.username.data
            if form.password.data:
                setattr(user, "password", form.password.data)

            db.add(user)
            db.commit()
        except IntegrityError:
            db.rollback()
            data["errors"].append("Wrong email address or username")
        except ValueError as e:
            data["errors"].append(str(e))
    else:
        data["errors"] = form.errors

    if data["errors"]:
        data["message"] = "Error while saving data"
        return jsonify(data), 400
    else:
        data["message"] = "Changes saved"
        return jsonify(data)

@blueprint.subdomain_route("/enroll/<course_slug>", methods=["POST"])
def enroll(course_slug, institute=""):
    """
    Enroll a user into a course.
    """
    course = datamodels.get_course_by_slug(course_slug)
    if course is None:
        return abort(404)

    course_code = request.form.get("course_code", "")

    if (
        course.visibility == "code"
        and course_code.lower() != course.course_code.lower()
    ):
        flash("Wrong course code")
        return redirect("/course/{}".format(course.slug))

    user = get_current_user()
    if course.guest_access and not user:  # Guest access for not log in user
        sess = session.get("enrollments", "[]")
        data = json.loads(sess)
        if course.id in data:
            return redirect(course.lessons[0].permalink)
        else:
            data.append(course.id)
            session["enrollments"] = json.dumps(data)
    elif not course.guest_access and not user:
        return redirect("/login")
    else:
        course.enroll(user)

    flash("You are now enrolled in {}".format(course.title))
    return redirect(course.lessons[0].permalink)


@blueprint.subdomain_route("/login", methods=["GET", "POST"])
def login(institute=""):
    """ Validate login and save current user to session. """
    return current_app.auth0.authorize_redirect(redirect_uri='{}/callback'.format('{}://{}'.format(current_app.config['HTTP_SCHEME'], current_app.config['SERVER_NAME'])))


@blueprint.subdomain_route("/logout", methods=["GET", "POST"])
@login_required
def logout(user, institute=""):
    """ Clear session data, logging the current user out. """
    # Clear session stored data
    session.clear()
    flash("You have been successfully logged out.")
    # Redirect user to logout endpoint
    params = {'returnTo': '{}://{}'.format(current_app.config['HTTP_SCHEME'], current_app.config['SERVER_NAME']), 'client_id': current_app.config['AUTH0_CLIENT_ID']}
    return redirect(current_app.auth0.api_base_url + '/v2/logout?' + urlencode(params))

@blueprint.subdomain_route("/callback", methods=["POST", "GET"])
def callback(institute=""):
    """
    Handle the Auth0 callback after login.
    """
    # Handles response from token endpoint
    last_page = request.args.get("last_page", "")
    data = {"errors": [], "last_page": last_page, "form": []}
    try:
        # Look for the current user
        current_app.auth0.authorize_access_token()
        resp = current_app.auth0.get('userinfo')
        userinfo = resp.json()
        db = datamodels.get_session()
        user = datamodels.get_user_by_auth0_id(userinfo['sub'])
        if user is None:
            user = datamodels.get_user_by_email(userinfo['email'])
            if user is not None:
                # User is registered with email, but hasn't signed in w/ Auth0 yet
                user.auth0_id = userinfo['sub']
                db.commit()
            elif user is None:
                # Register a new user.
                try:
                    user = datamodels.User()
                    user.email = user.username = userinfo['email']
                    user.first_name = userinfo['given_name']
                    user.last_name = userinfo['family_name']
                    user.auth0_id = userinfo['sub']
                    db.add(user)
                    db.commit()
                except Exception as e:
                    data["errors"].append("{}".format(e))
                    return render_template("welcome.html", **data)
                if "enrollments" in session:
                    d = get_session_data(session, "enrollments")
                    for course_id in d:
                        course = datamodels.Course.find_by_id(int(course_id))
                        if course:
                            course.enroll(user)
                if "anon_progress" in session:
                    d = get_session_data(session, "anon_progress")
                    merge_anonymous_data(user.id, d)
                    session.pop("anon_progress")
                if "anon_surveys" in session:
                    d = get_session_data(session, "anon_surveys")
                    merge_anonymous_surveys_data(user.id, d)
                    session.pop("anon_surveys")
        session["user_id"] = user.id
        session['jwt_payload'] = userinfo
        session['profile'] = {
            'user_id': userinfo['sub'],
            'name': userinfo['name'],
            'picture': userinfo['picture']
        }
    except Exception as e:
        data["errors"].append("{}".format(e))
        return render_template("welcome.html", **data)
    return redirect(last_page or "/")

@blueprint.subdomain_route("/preference/<preference_tag>/<on_or_off>", methods=["POST"])
@login_required
def set_preference(user, preference_tag, on_or_off, institute=""):
    """ Set a user preference. """
    if preference_tag not in PreferenceTags:
        flash("Unknown preference.")
        return "Unknown preference tag."
    if on_or_off in ["ON", "on"]:
        value = True
    elif on_or_off in ["OFF", "off"]:
        value = False
    else:
        flash("Unknown preference setting.")
        return "Unknown preference setting."
    user.set_preference(preference_tag, value)
    return ""


@blueprint.subdomain_route("/user/settings", methods=["POST"])
def set_user_setting(institute=""):
    form = CustomSettingForm(request.form)
    user = get_current_user()
    if form.validate():
        key = form.key.data
        value = form.value.data
        if key not in datamodels.CUSTOM_SETTINGS_KEYS:
            return jsonify({"message": "There is no such setting available"}), 400
        if user:
            datamodels.CustomSetting.set_setting(key, value, user)
        else:
            custom_settings = get_session_data(session, "custom_settings")
            custom_settings[key] = value
            set_session_data(session, "custom_settings", custom_settings)
        return jsonify({"key": key, "value": value})
    else:
        if "csrf_token" in form.errors:
            msg = "CSRF token missing"
        else:
            msg = "Both key and value must be provided"
        return jsonify({"message": msg}), 400


@blueprint.subdomain_route("/user/settings", methods=["GET"])
def get_user_settings(institute=""):
    user = get_current_user()
    if user:

templates/partials/nav/_footer.html
<footer>
  <div class="fit_course">
    <div class="container-fluid">

      <div class="row">
        <div class="col-sm">
          <a href="/" class="fit_device">
            {% include 'partials/chrome/_fa_svg_square.html' %}
          </a>
        </div>
        <div class="col-sm">
          <div class="fit_footer_nav">
            {{ link_to('courses.index', 'Courses 🥰')}}
            {{ link_to('about.services', 'Services')}}
          </div>
        </div>
        <div class="col-sm">
          <div class="fit_footer_nav">
            {{ link_to('about.index', 'About us')}}       
            {{ link_to('about.mistakes', 'Mistakes')}}
            {{ link_to('about.michael', 'Michael')}}
            <a href="https://medium.com/fitzroy-academy" target="_blank">Blog <i class="far fa-external-link"></i></a>
          </div>
        </div>
        <div class="col-sm">
          <div class="fit_footer_nav">
            {{ link_to("support.index", "Support") }}
            {{ link_to('support.contact', 'Contact us')}}            
            {{ link_to("support.terms", "Terms")}}
            {{ link_to("support.privacy", "Privacy")}}
            {{ link_to("support.conduct", "Conduct")}}            
          </div>
        </div>
        <div class="col-sm">
          <div class="fit_footer_nav">
            <a href="/support" class="note"><small>Need help?</small>Get support</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/partials/nav/_header_back.html
<a href="/" class="fit_btn left"> 
  <i class="fas fa-arrow-left"></i>
  <span class="fit_txt">Back</span>
</a>

templates/partials/nav/_header_back_coursetitle.html
<a href="/course/{{ course.slug }}" class="fit_btn left"> 
  <i class="fas fa-arrow-left"></i>
  <span class="fit_txt">{{ course.title }}</span>
</a>

templates/partials/nav/_header_home.html
<a href="/" class="fit_btn left"> 
  <i class="fas fa-arrow-left"></i>
  <span class="fit_txt">Home</span>
</a>

templates/partials/nav/_header_link_back.html
<a href="/" class="fit_btn left"> 
  <i class="fas fa-arrow-left"></i>
  <span class="fit_txt">Back</span>
</a>

templates/partials/nav/_header_link_coursetitle.html
<a href="/course/{{ course.slug }}" class="fit_btn left"> 
  <i class="fas fa-arrow-left"></i>
  <span class="fit_txt">{{ course.title }}</span>
</a>

templates/partials/nav/_header_link_home.html
<a href="/" class="fit_btn left"> 
  <i class="fas fa-arrow-left"></i>
  <span class="fit_txt">Home</span>
</a>

templates/partials/nav/_header_link_user.html
<a href="/edit" class="fit_btn" data-fit-userpanel>
  <span class="fit_txt">
    <span class="d-none d-sm-inline-block">{{ current_user.first_name }}</span>
    <span class="d-none d-md-inline-block">{{ current_user.last_name }}</span>
  </span>
  <span class="fit_pic circle">
      {% if current_user.profile_picture %}
          <img src="{{ current_user.profile_picture_url }}" alt="user">
      {% else %}
            <i class="fas fa-user" style="opacity: 100;"></i>
      {% endif %}

  </span>
</a>

templates/partials/nav/_header_loading.html
<div class="fit_loading spinner">
	<div class="circle">
		<i class="fas fa-spin fa-spinner-third"></i>
	</div>
</div>

<div class="fit_loading check">
	<div class="circle">
		<i class="fas fa-check"></i>
	</div>
</div>

<div class="fit_loading error">
	<div class="circle">
		<i class="fas fa-exclamation"></i>
	</div>
</div>

templates/partials/nav/_header_nav_sales.html
<div class="right fit_mobile_menu">

  <a href="{{ url_for('course.index') }}" class="fit_btn fit_mobile_menu_trigger" data-fit_mobile_menu_trigger>
    <span class="fit_txt">Menu</span>
    <i class="fal fa-chevron-down"></i>
    <i class="fal fa-times"></i>
  </a>

  <div class="right fit_mobile_menu_dropdown">

    <form class="form fit_search_header" action="/search" method="post">
      <input class="form-control" type="text" value="" placeholder="Search..." data-fit_search_header_input>
      <button class="btn btn-link"><i class="fal fa-search"></i></button>
      <a href="#" class="btn btn-link" data-fit_toggle_mode="fit_search_header_active"><i class="fal fa-times"></i></a>
      <div class="results"></div>
    </form>

    <a href="/search" class="fit_btn search d-none" data-fit_toggle_mode="fit_search_header_active" data-fit_focus="[data-fit_search_header_input]">
      <i class="fal fa-search"></i>
      <span class="fit_txt">Search</span>
    </a>

    <a href="{{ url_for('about.index') }}" class="fit_btn">
      <span class="fit_txt">About</span>
    </a>

    <a href="{{ url_for('product.index') }}" class="fit_btn">
      <span class="fit_txt">Product</span>
    </a>
<!-- 
    <a href="{{ url_for('product.pricing') }}" class="fit_btn">
      <span class="fit_txt">Pricing</span>
    </a>
 -->
<!--     <a href="{{ url_for('product.teachers') }}" class="fit_btn">
      <span class="fit_txt">Teachers</span>
    </a>
 -->
    <a href="{{ url_for('support.index') }}" class="fit_btn">
      <span class="fit_txt">Support</span>
    </a>
  
    {% if current_user %}
      
      {% include 'partials/nav/_header_link_user.html' %}

    {% else %}

      <a href="{{ url_for('user.login') }}" class="fit_btn login" data-fit-userpanel>
        <span class="fit_txt">Sign up / Log in</span>
        <i class="fal fa-user"></i>
        <i class="fal fa-chevron-right"></i>
      </a>
    
    {% endif %}

  </div>
</div>

templates/partials/nav/_header_sales_nav.html
<div class="right fit_mobile_menu">

  <a href="{{ url_for('index') }}" class="fit_btn fit_mobile_menu_trigger" data-fit_mobile_menu_trigger>
    <span class="fit_txt">Menu</span>
    <i class="fal fa-chevron-down"></i>
    <i class="fal fa-times"></i>
  </a>

  <div class="right fit_mobile_menu_dropdown">

    <form class="form fit_search_header" action="/search" method="post">
      <input class="form-control" type="text" value="" placeholder="Search..." data-fit_search_header_input>
      <button class="btn btn-link"><i class="fal fa-search"></i></button>
      <a href="#" class="btn btn-link" data-fit_toggle_mode="fit_search_header_active"><i class="fal fa-times"></i></a>
      <div class="results"></div>
    </form>

    <a href="/search" class="fit_btn search d-none" data-fit_toggle_mode="fit_search_header_active" data-fit_focus="[data-fit_search_header_input]">
      <i class="fal fa-search"></i>
      <span class="fit_txt">Search</span>
    </a>

    <a href="{{ url_for('about.index') }}" class="fit_btn">
      <!-- <i class="fal fa-question-circle"></i> -->
      <span class="fit_txt">About</span>
    </a>

    <a href="{{ url_for('product.index') }}" class="fit_btn">
      <!-- <i class="fal fa-question-circle"></i> -->
      <span class="fit_txt">Product</span>
    </a>

    <a href="{{ url_for('support.index') }}" class="fit_btn">
      <!-- <i class="fal fa-question-circle"></i> -->
      <span class="fit_txt">Support</span>
    </a>
  
    {% if current_user %}
      
      {% include 'partials/nav/_header_userlink.html' %}

    {% else %}

      <a href="{{ url_for('user.login') }}" class="fit_btn login" data-fit-userpanel>
        <span class="fit_txt">Sign up</span>
        <i class="fal fa-user"></i>
        <i class="fal fa-chevron-right"></i>
      </a>
    
    {% endif %}

  </div>
</div>

templates/partials/nav/_sidepanel_login.html
<div class="fit_sidepanel userpanel">
  <div class="whiteout" data-fit-userpanel></div>
  <div class="panel">
  
    <div class="head">
      <a href="{{ url_for('user.login') }}" class="fit_btn right" data-fit-userpanel>
        <span class="fit_txt">Close</span>
        <i class="far fa-times"></i>
      </a>
    </div>
    
    <div class="content">
      
      {% if current_section != 'login' %}
        {% include 'partials/form/_login.html' %}
      {% endif %}

    </div>

  </div>
</div>

templates/partials/nav/_user_loggedin.html
<header>
  
  <a href="/" class="fit_btn left"> 
    <i class="fas fa-arrow-left"></i>
    <span class="fit_txt">Home</span>
  </a>

  <a href="user.html" class="fit_btn right" data-fit-userpanel>
    <span class="fit_txt">
      <span class="d-none d-sm-inline-block">{{ current_user.first_name }}</span>
      <span class="d-none d-md-inline-block">{{ current_user.last_name }}</span>
    </span>
    <span class="fit_pic circle"> 
      <!-- DEV: if profile picture exists show: -->
        <img src="{{ current_user.profile_picture }}" alt="user">
      <!-- DEV: otherwise, show this icon:
        <i class="fal fa-user"></i>
       -->
    </span>
  </a>

</header>

<div class="fit_sidepanel userpanel">
  <div class="whiteout" data-fit-userpanel></div>
  <div class="panel">
  
    <div class="head">
      <a href="user.html" class="fit_btn right" data-fit-userpanel>
        <span class="fit_txt">
          {{ current_user.full_name }}
        </span>
        <i class="fas fa-times"></i>
      </a>
    </div>
    
    <div class="content">
      
      <div class="fit_pane">
        <dl class="fit_summary_icons">
          <dt><i class="far fa-user"></i> About you.</dt>
          <dd>
            <ul>
              <li>{{ current_user.full_name }}</li> 
              <li><a href="mailto:{{ current_user.email }}">{{ current_user.email }}</a></li> 
              <!-- <li><strong>34</strong> years old, from <strong>Paris, France</strong>.</li> <! DEV: from the user DB -->
            </ul>
            
            <form method="post" action="/logout" class="form-inline">
              <a href="{{ url_for('user.edit') }}" class="btn btn-outline-primary btn-sm"><i class="fas fa-edit"></i> Edit your details</a>
              &nbsp; 
              <button type="submit" class="btn btn-outline-secondary btn-sm"><i class="fas fa-sign-out"></i> Log out</button>
            </form>
          </dd>
        </dl>
      </div>        
      <div class="fit_course">
        <h3>
          <span class="txt">Your courses.</span>
          <small class="subtxt"><span class="fas fa-check"></span> 72% complete</small> <!-- DEV: total % complete, aggregated across all courses user has started -->
        </h3>

        <div class="fit_body fit_lessons">

          <!-- DEV: this is links (without the accordion!) direct to the courses user is enrolled in -->

          <div class="fit_lesson">
            <a class="fit_btn collapsed i-l i-t" href="#">
              <div class="fit_pic vid">
                <img src="/assets/images/lessons/agile-project-management.jpg" alt="course">
                <span class="fas fa-check"></span>
              </div>
              <span class="fit_txt">Agile project management</span>
              <span class="fit_txt secondary">Clare Carmody, Salesforce</span>
              <span class="fit_time">43:51</span>
            </a>
          </div>

          <div class="fit_lesson">
            <a class="fit_btn collapsed i-l i-t" href="#">
              <div class="fit_pic vid">
                <img src="/assets/images/lessons/guerilla-usability-testing.jpg" alt="course">
                <span class="fas fa-check"></span>
              </div>
              <span class="fit_txt">Feeling good about eating cake</span>
              
              <span class="fit_txt secondary">Melissa Ng, Melewi</span>
              <span class="fit_time">53:51</span>
            </a>        
          </div>            


          <div class="fit_lesson">
            <a class="fit_btn collapsed i-l i-t" href="#">
              <div class="fit_pic vid">
                <img src="/assets/images/lessons/crowdfunding.jpg" alt="course">
                <span class="fas fa-play"></span>
              </div>
              <span class="fit_txt">Crowdfunding</span>
              
              <span class="fit_txt secondary">Prashan Paramanathan, Chuffed</span>            
              <span class="fit_time">3:51</span>
            </a>
          </div>
        </div>
      </div><!-- fit_course -->
      <!-- end vid stack -->

      <h3>
        <span class="txt">Your privacy.</span>
      </h3>
      <p></p>
      <dl class="fit_summary_icons">
        <dt><i class="far fa-lock"></i> Notifications.</dt>
        <dd>
          <div class="form-group">
            <input type="checkbox" checked data-toggle="toggle" data-size="sm" data-style="simple" id="permissions_1" name="permissions_1"> <!-- DEV: user privacy permissions. Let's talk this through -->
            <label for="permissions_1">Receieve emails and notifications from your teachers.</label>
          </div>
          <div class="form-group">
            <input type="checkbox"  data-toggle="toggle" data-size="sm" data-style="simple" id="permissions_1" name="permissions_1"> <!-- DEV: user privacy permissions. Let's talk this through -->
            <label for="permissions_1">Receieve emails and notifications from <a href="/">Fitzroy Academy</a>.</label>
          </div>
        </dd>
        <dt><i class="far fa-lock"></i> Your details and data.</dt>
        <dd>     
          <div class="form-group">
            <input type="checkbox" checked data-toggle="toggle" data-size="sm" data-style="simple" id="permissions_1" name="permissions_1"> <!-- DEV: user privacy permissions. Let's talk this through -->
            <label for="permissions_1">Let us use your learning data for research. <a href="/faq#research">What&rsquo;s this?</a></label>
          </div>
          <div class="form-group">
            <input type="checkbox" checked data-toggle="toggle" data-size="sm" data-style="simple" id="permissions_1" name="permissions_1"> <!-- DEV: user privacy permissions. Let's talk this through -->
            <label for="permissions_1">Allow other students to see my name</label>
          </div>
          <div class="form-group">
            <input type="checkbox" checked data-toggle="toggle" data-size="sm" data-style="simple" id="permissions_1" name="permissions_1">  <!-- DEV: user privacy permissions. Let's talk this through -->
            <label for="permissions_1">Allow other registered users to see my email address</label>
          </div>
        </dd>          
      </dl>
      <p>Not sure about privacy or data? <a href="/faq#privacy">Read the FAQs</a> about our data and research.</p>
    </div>

  </div>
</div>

templates/partials/nav/_user_login.html
<header>

  <div class="container">
    <a href="/" class="fit_btn left"> 
      <!-- DEV: this will link to the previous 'bit' of the app, i.e. from a lesson back to a course, course back to course intro, course intro back to home.... When in doubt ask Will! -->
      <i class="fas fa-arrow-left"></i>
      <span class="fit_txt">Back</span>
    </a>

    <a href="/login" class="fit_btn right" data-fit-userpanel>
      <span class="fit_txt">Sign in</span>
      <i class="fal fa-user"></i>
    </a>

  </header>

  <div class="fit_sidepanel userpanel">
    <div class="whiteout" data-fit-userpanel></div>
    <div class="panel">
    
      <div class="head">
        <a href="/login" class="fit_btn right" data-fit-userpanel>
          <span class="fit_txt">
            Sign in
          </span>
          <span class="fit_pic circle">
            <i class="far fa-times"></i>
          </span>
        </a>
      </div>
      
      <div class="content">
        
        {% include 'partials/_login_form.html' %}

      </div>

    </div>
  </div>
</div>